// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSa91zZdJD-hyTkXas22i8XQUIaeibYd0',
    appId: '1:483173610990:web:49d9c3d5658ab24ceb4aff',
    messagingSenderId: '483173610990',
    projectId: 'linelifemain',
    authDomain: 'linelifemain.firebaseapp.com',
    databaseURL: 'https://linelifemain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'linelifemain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZgkaTN1J5JcLh7ZLMz0MYeVZJR0kqdE',
    appId: '1:483173610990:android:6028754811022c18eb4aff',
    messagingSenderId: '483173610990',
    projectId: 'linelifemain',
    databaseURL: 'https://linelifemain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'linelifemain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_EKENLGDu10SZ8hFUKrO9QzFdAnjVBok',
    appId: '1:483173610990:ios:1978e0aa8c9defcceb4aff',
    messagingSenderId: '483173610990',
    projectId: 'linelifemain',
    databaseURL: 'https://linelifemain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'linelifemain.appspot.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_EKENLGDu10SZ8hFUKrO9QzFdAnjVBok',
    appId: '1:483173610990:ios:1978e0aa8c9defcceb4aff',
    messagingSenderId: '483173610990',
    projectId: 'linelifemain',
    databaseURL: 'https://linelifemain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'linelifemain.appspot.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSa91zZdJD-hyTkXas22i8XQUIaeibYd0',
    appId: '1:483173610990:web:2587b323da3917ddeb4aff',
    messagingSenderId: '483173610990',
    projectId: 'linelifemain',
    authDomain: 'linelifemain.firebaseapp.com',
    databaseURL: 'https://linelifemain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'linelifemain.appspot.com',
  );
}
